authe/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from . import views

app_name = 'authe'

urlpatterns = [
    path('signup/',views.SignUpUser.as_view(), name='signup'),
    path('signin/',views.SignInUser.as_view() ,name='signin'),
    path('signout/',views.signout_user , name='signout'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),


    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/token/user/', views.UserViewSet.as_view({'get':'retrieve', 'post':'create'}))
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view

app_name = 'films'
schema_view = get_swagger_view(title='rezkapoisk API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('films/', include('films.urls')),
    path('authe/', include('authe.urls')),
    path('swagger/', schema_view),
]

if settings.DEBUG:     # Подключение пути url до фото #
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from . import views

# router = SimpleRouter()     # Работает по viewset #
# router.register(r'', views.FilmViewSet, basename='kino')     

app_name = 'films'

urlpatterns = [
    path('', views.Home, name="home"),
    path('films/<int:genres_id>/', views.genre_f, name="genres"),
    path('search/', views.FilmSearchView.as_view(), name='film-search'), 
    path('add/', views.AddFilm.as_view(), name='add'),
    path('delete_film/<int:film_id>/', views.delete_film, name='delete'), 
    path('edit_film/<int:film_id>/', views.EditFilm.as_view(), name='edit'),
    path('filmsl/<int:film_id>/<str:film_name>/', views.films_l, name='filmsl'),
    path('films_remove/<int:film_id>/<str:film_name>/', views.films_remove, name='films_remove'),


    path('cmadd/', views.AddComment.as_view(), name='cmadd'),
    path('testcommentview/<int:blog_id>/', views.FilmDetail.as_view(), name='comments-category'),
    path('delete_comment/<int:blog_id>/', views.delete_comment, name='delete-comment'), 



    path('api', views.FilmListAPIView.as_view()),
    path('<int:pk>/',views.FilmDetailAPIView.as_view()),
    path('auth/', include('rest_framework.urls')),


    # path('', views.FilmViewSet.as_view({'get':'list'})),
    # path('<int:pk>/',views.FilmViewSet.as_view({'get':'retrieve'}))
    # path('', include(router.urls)),
]

authe/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
import uuid


# Create your models here.
class User(AbstractUser):
    image = models.ImageField(upload_to='avatars', blank=True)

    groups = models.ManyToManyField(
        'auth.Group',          
        related_name='users',
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='users',
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
        error_messages={
            'add': 'The permission you are trying to add already exists for the user.',
            'remove': 'The permission you are trying to remove does not exist for the user.',
        },
    )

authe/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.db import models
from PIL import Image
from .models import *

class SignUpUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('image','username', 'email','first_name', 'last_name', 'password1', 'password2',)

        widgets = {
            'username': forms.TextInput(attrs={'class':'from-input'}),
        }       

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('image','username', 'email','first_name', 'last_name',)

authe/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, login
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from rest_framework.generics import RetrieveAPIView
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from rest_framework import mixins
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from rest_framework.generics import RetrieveAPIView
from rest_framework.viewsets import GenericViewSet
from rest_framework import response
from rest_framework import mixins
from  .models import *
from .serializer import *
from .forms import *
from films.models import Film, LikedFilm


# Create your views here.
menu = [
    {'title':'Home', 'url':'films:home'},
    {'title':'Description', 'url':'films:category'},
    {'title':'Регистрация', 'url':'authe:signup'},
    {'title':'Вход', 'url':'authe:signin'}
]
class UserDetailAPIView(RetrieveAPIView):
    
    def get_queryset(self):
        return User.objects.get(id=self.request.user.id)
    
class UserViewSet(GenericViewSet, mixins.CreateModelMixin, ):
    def get_queryset(self):
        if self.action == 'retrieve':
            return User.objects.get(id=self.request.user.id)
        return User.objects.all()

    def get_serializer_class(self):
        if self.action == 'create':
            return UserCreateSerializer
        elif self.action == 'retrieve':
            return UserRetrieveSerializer
        
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_queryset()
        serializer = self.get_serializer(instance)
        return response(serializer.data)

# Create your views here.

class SignUpUser(CreateView):
    form_class = SignUpUserForm
    template_name = 'authe/signup.html'
    success_url = reverse_lazy('films:home')     # Переход после создания пользователя #

    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)

        context['title'] = 'Регистрация'
        context['menu'] = menu

        return context
    
class SignInUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'authe/signin.html'


    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)

        context['title'] = 'Авторизация'
        context['menu'] = menu

        return context
    
    def get_success_url(self):
        return reverse_lazy('films:home')



class UserDetailAPIView(RetrieveAPIView):
    def get_queryset(self):
        return User.objects.get(id=self.request.user.id)
    
class UserViewSet(GenericViewSet, mixins.CreateModelMixin,):
    def get_queryset(self):
        if self.action == 'retrieve':
            return User.objects.get(id=self.request.user.id)
        return User.objects.all()

    def get_serializer_class(self):
        if self.action == 'create':
            return UserCreateSerializer
        elif self.action == 'retrieve':
            return UserRetrieveSerializer
        
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_queryset()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

def signout_user(request):             # Выход из аккаунта  #
    logout(request)   
    return redirect('authe:signin')     

def profile(request):
    if not request.user.is_authenticated:
        return redirect('authe:signin')
    
    # Список понравившихся фильмов текущего пользователя #
    user_liked_films = LikedFilm.objects.filter(user=request.user)

    # Извлечь фильмы из объектов #
    liked_films = [liked_film.film for liked_film in user_liked_films]

    data = {
        'title': 'Профиль',
        'menu': menu,
        'user_liked_films': liked_films,}
     
    return render(request, 'authe/profile.html', data)




@login_required             # Только зарегистрированные user-ы #
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user) # использование данных user-a для редактирования #
        if form.is_valid():
            form.save()
            return redirect('authe:profile')  
    else:
        form = EditProfileForm(instance=request.user)
    
    return render(request, 'authe/edit-profile.html', {'form': form})

authe/templates/authe/edit-profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit profile</title>
    <link rel="stylesheet" href="{% static 'authe/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'authe/css/authe.css' %}">
</head>
<body>
    <header>
        <h1>Rezkapoisk</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'films:film-search'  %}" class="form">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    Search
                </button> 
            </form> 
        </div>

        <div class="header-div-2">
            <a href="{% url 'films:home' %}" class="button-reg">Home</a>
            <a href="{% url 'authe:signout' %}" class="button-reg">Signout</a>
            {% if user.image %}
                <a href="{% url 'authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
            {% else %}
                <a href="{% url 'authe:profile'%}"><img src="{% static 'films/images/User.png' %}" alt=""></a>
            {% endif %}
        </div>
    </header>
    <hr id="hr-line">

    <section class="authe-main">
        <h1>Редактирование профиля</h1>
        <form method="post" class="authe-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
    </section>
</body>
</html>  

authe/templates/authe/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Профиль</title>
    <link rel="stylesheet" href="{% static 'authe/css/authe.css' %}">
    <link rel="stylesheet" href="{% static 'authe/css/Header.css' %}">

</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'films:film-search'  %}" class="form">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    Search
                </button>
            </form> 
        </div>

        <div class="header-div-2">
            <a href="{% url 'films:home' %}" class="button-reg">Home</a>
            <a href="{% url 'authe:signout' %}" class="button-reg">Signout</a>
            {% if user.image %}
                <a href="{% url 'authe:profile'%}"><img src="{{ user.image.url }}" alt="" id="header-img"></a>
            {% else %}
                <a href="{% url 'authe:profile'%}"><img src="{% static 'films/images/User.png' %}" alt=""></a>
            {% endif %}
        </div>
    </header>
    <hr id="hr-line">
    
    <section class="main">
        <div class="com-blog">
            {% for f in user_liked_films %}
            <div class="main-info"> 
                {% if f.poster %}
                    <img src="{{ f.poster.url }}" alt="comment-img" class="film-img">
                {% endif %}
            </div>
            <hr>
            <h4 class="blog-name">{{ f.title_ru }}</h4>
            <h4 class="blog-name">{{ f.title_orig }}</h4>
            <h4>{{ f.timing }} мин</h4>
            <h4>{{ f.country }}</h4>
            <h4>{{ f.director }}</h4>
            <h4><time class="blog-name">{{ f.prod_year }} год</time></h4>
            <hr>

            <div class="blog-change">
                {% if request.user.is_staff %}
                    <a href="{% url 'films:delete' f.id %}" class="blog-button">Удалить фильм</a>
                    <a href="{% url 'films:edit' f.id  %}" class="blog-button">Изменить Фильм</a>
                {% endif %}
                <a href="{% url 'films:films_remove' f.id  f.title_ru %}" class="blog-button">удалить из понравившихся</a>
            </div>
            <hr>
            {% endfor %}
        </div>
    </section>

    <section class="profile-main">
        <span>
            {% if user.image %}
            <img src="{{ user.image.url }}" alt="" class="profile-img">
            {% else %}
                <img src="{% static 'decode_blogs/images/User.png' %}" alt=""></a>
            {% endif %}
        </span>
        <div class="profile-info">
            <p>
                <span>{{ user.username }}</span>
            </p>

            <p>
                <span>{{ user.first_name }}</span>
            </p>

            <p>
                <span>{{ user.last_name }}</span>
            </p>

            <p>
                <span>{{ user.email }}</span>
            </p>
        </div>

        {% if request.user.is_authenticated %}
            <div class="admin-links">
                <a href="{% url 'authe:edit-profile' %}" class="blog-button">Редактировать профиль</a>      
                <a href="{% url 'films:add' %}" class="blog-button"> Добавить новый фильм</a>
            </div>
        {% endif %}
    </section>
</body>
</html>

authe/templates/authe/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link rel="stylesheet" href="{% static 'authe/css/authe.css' %}">
    <link rel="stylesheet" href="{% static 'authe/css/header.css' %}">
</head>
<body>
    <header>
        <h1>Decode Blog</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'films:film-search'  %}" class="form">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по блогам" name="search">
                <button id="button-find">
                    Search
                </button>
            </form> 
        </div>


        <div class="header-div-2">
            <a href="{% url 'films:home' %}" class="button-reg">Home</a>
            <a href="{% url 'authe:signup' %}" class="button-reg">SignUp</a>    
        </div>
    </header>
    <hr id="hr-line">


    <section class="authe-main">
        <h1>Авторизация</h1>

        <form action="" method="POST" class="authe-form">
            {% csrf_token %}
            
            {{ form.as_p }}
            
            <button type="submit">Зарегистрироваться</button>
        </form>
    </section>
</body>
</html>

authe/templates/authe/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'authe/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'authe/css/authe.css' %}">
</head>
<body>
    <header class="header-1">
        <h1>Rezkapoisk</h1>
        <div class="header-div-1">
            <form method="POST" action="{% url 'films:film-search'  %}" class="form_1">
                {% csrf_token %}
                <input type="search" placeholder="Поиск по фильмам" name="search">
                <button id="button-find">
                    Search
                </button>
            </form> 
        </div>
    </header>
    <hr>


<section class="authe-main">
    <h1>Регистрация</h1>
    <form action="" method="POST" class="authe-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>
</section>
</body>
</html>